"use client";

import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { NavigationMenu } from "@radix-ui/react-navigation-menu";
import { AlertDialogHeader, AlertDialogFooter } from "@/ui/alert-dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction } from "@radix-ui/react-alert-dialog";
import { AppFooter } from "@/components/AppFooter";
import { ReactNode, useState } from "react";
import { SharedHeader } from "@/components/SharedHeader";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "GLBoard",
  description: "Generated by create next app",
};

interface AppLayoutProps {
  children: ReactNode;
  currentPage: string;
  onNavigate: (page: string) => void;
  onLogout: () => void;
  isLoggedIn: boolean;
  onLogin?: () => void;
  onSignup?: () => void;
  user?: { name: string; email: string };
}

export default function AppLayout({ children, currentPage, onNavigate, onLogout, isLoggedIn, onLogin, onSignup, user }: AppLayoutProps) {
  const [logoutDialogOpen, setLogoutDialogOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isSidebarExpanded, setIsSidebarExpanded] = useState(false);

  const handleLogoutClick = () => {
    setLogoutDialogOpen(true);
  };

  const confirmLogout = () => {
    setLogoutDialogOpen(false);
    onLogout();
  };

  const isLandingPage = currentPage === 'landing';
  const isAboutPage = currentPage === 'about';
  const isManualPage = currentPage === 'manual';
  const isDocumentationsPage = currentPage === 'documentations';

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    element?.scrollIntoView({ behavior: 'smooth' });
    setMobileMenuOpen(false);
  };


 return (
  <html lang="pt-BR">
    <body>
    <div className="min-h-screen bg-background flex flex-col">
      {/* Public Pages Navbar (SharedHeader) */}
      {!isLoggedIn && (
        <SharedHeader 
          onLogin={onLogin || (() => {})} 
          onNavigate={onNavigate}
          isLoggedIn={isLoggedIn}
          currentPage={currentPage}
        />
      )}

      {/* Logged-in Pages Navbar */}
      {isLoggedIn && (
        <SharedHeader 
          onLogin={() => {}} 
          onNavigate={onNavigate}
          isLoggedIn={isLoggedIn}
          userName={user?.name.split(' ')[0] || 'Usuário'}
          currentPage={currentPage}
        />
      )}

      {/* Main Content */}
      <main className="flex-1">{children}</main>

      {/* Footer */}
      <AppFooter />

      {/* Logout Confirmation Dialog */}
      <AlertDialog open={logoutDialogOpen} onOpenChange={setLogoutDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Deseja realmente sair do GLBoard?</AlertDialogTitle>
            <AlertDialogDescription>
              Você será redirecionado para a página inicial e precisará fazer login novamente para acessar seus jogos.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction onClick={confirmLogout} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
              Sim, sair
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
    </body>
    </html>
  );
}

