export interface Game {
  id: string;
  name: string;
  createdDate: string;
  phases: number;
  genre?: string;
  status: "development" | "testing" | "completed";
}

export const mockGames: Game[] = [
  {
    id: "1",
    name: "Hello Food",
    createdDate: "05 de Out, 2025",
    phases: 4,
    genre: "Quebra-cabeça Educacional",
    status: "development",
  },
  {
    id: "2",
    name: "Cadê minha pizza?",
    createdDate: "28 de Set, 2025",
    phases: 6,
    genre: "Aventura",
    status: "testing",
  },
  {
    id: "3",
    name: "Robô Euroi",
    createdDate: "15 de Set, 2025",
    phases: 3,
    genre: "Simulação",
    status: "completed",
  },
  {
    id: "4",
    name: "Matemágica",
    createdDate: "10 de Set, 2025",
    phases: 8,
    genre: "Educacional",
    status: "development",
  },
  {
    id: "5",
    name: "Missão Código",
    createdDate: "02 de Set, 2025",
    phases: 5,
    genre: "Programação",
    status: "completed",
  },
  {
    id: "6",
    name: "História Viva",
    createdDate: "30 de Ago, 2025",
    phases: 7,
    genre: "Narrativa",
    status: "testing",
  },
  {
    id: "7",
    name: "EcoPlanet",
    createdDate: "18 de Ago, 2025",
    phases: 6,
    genre: "Sustentabilidade",
    status: "development",
  },
  {
    id: "8",
    name: "Lógica Lab",
    createdDate: "12 de Ago, 2025",
    phases: 9,
    genre: "Puzzle",
    status: "completed",
  },
  {
    id: "9",
    name: "Geografia Quest",
    createdDate: "01 de Ago, 2025",
    phases: 4,
    genre: "Exploração",
    status: "testing",
  },
  {
    id: "10",
    name: "Alfabeto Turbo",
    createdDate: "20 de Jul, 2025",
    phases: 2,
    genre: "Infantil",
    status: "development",
  },
  {
    id: "11",
    name: "Física Divertida",
    createdDate: "12 de Jul, 2025",
    phases: 6,
    genre: "Ciências",
    status: "completed",
  },
  {
    id: "12",
    name: "Desafio dos Algoritmos",
    createdDate: "05 de Jul, 2025",
    phases: 10,
    genre: "Programação",
    status: "testing",
  },
  {
    id: "13",
    name: "Química Mania",
    createdDate: "29 de Jun, 2025",
    phases: 5,
    genre: "Laboratório",
    status: "development",
  },
  {
    id: "14",
    name: "Aventura Espacial",
    createdDate: "18 de Jun, 2025",
    phases: 8,
    genre: "Aventura",
    status: "completed",
  },
  {
    id: "15",
    name: "Cidade Sustentável",
    createdDate: "07 de Jun, 2025",
    phases: 3,
    genre: "Simulação",
    status: "testing",
  },
  {
    id: "16",
    name: "Memória Ninja",
    createdDate: "30 de Mai, 2025",
    phases: 2,
    genre: "Memória",
    status: "completed",
  },
  {
    id: "17",
    name: "Missão Frações",
    createdDate: "22 de Mai, 2025",
    phases: 4,
    genre: "Matemática",
    status: "development",
  },
  {
    id: "18",
    name: "Bio Explorer",
    createdDate: "10 de Mai, 2025",
    phases: 6,
    genre: "Biologia",
    status: "testing",
  },
  {
    id: "19",
    name: "Trânsito Seguro",
    createdDate: "28 de Abr, 2025",
    phases: 3,
    genre: "Conscientização",
    status: "completed",
  },
  {
    id: "20",
    name: "Desafio das Cores",
    createdDate: "15 de Abr, 2025",
    phases: 1,
    genre: "Infantil",
    status: "development",
  },
];
